### ISSUE TITLE
使用CMSIS-Core 不是在構建目錄中

### ISSUE THREAD

**Issue by rxin-1219** [RT-Thread-packages/CMSIS_5_AUX#1]
![image](https://user-images.githubusercontent.com/76082025/166917061-370b6e1c-4452-4dac-a1cb-6b420d98ebcc.png)
請問如何使CMSIS-Core 在構建目錄中?
感謝

**Comment by mysterywolf** [comment]
你好 你可以修改src列表，将需要的h和c文件添加到列表中
https://github.com/RT-Thread-packages/CMSIS_5_AUX/blob/master/SConscript#L6-L7
https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32l475-atk-pandora/applications/SConscript

**Comment by rxin-1219** [comment]
你好
從錯誤中顯示是 __SXTB16_RORn 未定義
而我查看 __SXTB16_RORn 是定義在 CMSIS/Core/Incloud/cmsis_gcc.h中
![image](https://user-images.githubusercontent.com/76082025/167082592-0db53148-ed65-46b7-a65c-e24ad10025bf.png)
![image](https://user-images.githubusercontent.com/76082025/167082714-f6e4edf9-7031-44fa-bae7-e9de1dad1bb3.png)
從我的CMSIS/Core/Incloud/也確實有寫在SConscript中
![image](https://user-images.githubusercontent.com/76082025/167083932-831df355-8870-4074-9eb3-b05a18b0d33d.png)

但卻還是無法構建
是我有哪個地方寫錯嗎?

謝謝

**Comment by mysterywolf** [comment]
你好 请问你用slack吗 你用你的邮箱ping我一下我的邮箱

**Comment by rxin-1219** [comment]
剛剛有ping你了

**Comment by mysterywolf** [comment]
meco@rt-thread.org 我没有收到
